create table csml_record_metrics
(
    id_record                                                 integer not null
        primary key
        constraint csml_record_metrics_csml_record_id_record_fk
            references csml_record,
    incites_times_cited                                       integer,
    incites_journal_expected_citations                        numeric(10, 3),
    incites_category_expected_citations                       numeric(10, 3),
    incites_journal_normalized_citation_impact                numeric(10, 3),
    incites_category_normalized_citation_impact               numeric(10, 3),
    incites_percentile_in_subject_area                        numeric(10, 3),
    incites_journal_impact_factor                             numeric(10, 3),
    jcr_quartile                                              text,
    jcr_quartile_count                                        integer,
    snip_current                                              numeric(10, 3),
    sjr_current                                               numeric(10, 3),
    snip_quartile_max                                         text,
    snip_quartile_count                                       integer,
    sjr_quartile_max                                          text,
    sjr_quartile_count                                        integer,
    jcr_journal_impact_factor                                 numeric(10, 3),
    jcr_journal_5_year_impact_factor                          numeric(10, 3),
    count_au_from_urfu                                        integer,
    fieldweightedviewimpact                                   numeric(10, 3),
    fieldweightedcitationimpact                               numeric(10, 3),
    views                                                     integer,
    outputsintopcitationpercentilesperpercentile              integer,
    fieldweightedoutputsintopcitationpercentilesperpercentile integer,
    citescore_current                                         numeric(10, 3),
    faculty                                                   text,
    subject                                                   text,
    cited_koef                                                numeric(5, 3),
    priority_koef                                             integer,
    cited_koef_final                                          integer,
    subject_all                                               text,
    cited_from_prev_calculus                                  integer,
    numberofauthors                                           integer,
    count_asjc                                                integer,
    count_qs                                                  integer,
    count_asjc_not_in_masterlist                              integer default 0,
    count_asjc_masterlist                                     integer,
    count_qs_masterlist                                       integer,
    count_the_masterlist                                      integer,
    count_the                                                 integer,
    sjr_in_year                                               numeric(10, 3),
    snit_in_year                                              numeric(10, 3),
    top25_sinp                                                integer,
    count_aff                                                 integer,
    count_country                                             integer,
    snip_in_year_cwts                                         numeric(10, 3),
    snip_in_year_cwts_q                                       integer,
    snippercentile                                            numeric(10, 3),
    citescorepercentile                                       numeric(10, 3),
    sjrpercentile                                             numeric(10, 3),
    count_au_from_org_know                                    integer
);

